### ISSUE TITLE
Hos geldin mesaji

### ISSUE THREAD

**Issue by bilgekaan** [erenertugrul/construct-discord-bot#8]
**Hata kısa açıklaması**

Hos geldin ayri yazilmali bir de buyuk harfle baslamis cumle ortasinda

"Construct Türkiye kanalına Hoşgeldin x. Kullanabileceğin komut listesini görmek için !yardim yazabilirsin. :)"

bu sekilde olmali:

"Construct Türkiye kanalına hoş geldin x. Kullanabileceğin komut listesini görmek için !yardim yazabilirsin. :)"

**Ekran görüntüleri**

**Comment by erenertugrul** [comment]
Düzeltildi.
